{
  "hash": "15e968a25665f4eb87a09eb142ca6184",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n::: {.content-hidden when-format=\"pdf\"}\n\\newcommand{\\E}{\\mathbf{E}} \n\\DeclareMathOperator{\\Var}{Var}\n\\DeclareMathOperator{\\Cov}{Cov}\n\\DeclareMathOperator{\\corr}{corr}\n\\DeclareMathOperator{\\sd}{sd}\n\\newcommand{\\se}{\\mathsf{se}}\n:::\n\n\n\n\n# Exploratory data analysis {#sec-eda}\n\nExploratory data analysis (EDA) is the process of understanding a data set before performing formal inference or fitting a statistical model. The goal is to identify the important features of the data (and any problems) early.\n\n:::{.callout-tip}\n## In practice, EDA answers questions like:\n\n- What are the variables and units?\n- How much missing data is there?\n- What do the marginal distributions look like?\n- Are there outliers or data errors?\n- Which variables appear associated?\n:::\n\n## A first look in R\n\n:::{.callout-note collapse=\"true\"}\n## Cyclamen Data\n\nThe **Cyclamen Data** contain 150 obs. of six features (sequence [], petal length [mm], petal width [mm], aperture diameter [mm], color [pink, white], and group [alpha, beta, gamma, delta, epsilon]) for *cyclamen hederifolium*. These measurements were taken by small groups of former MA22004 students using the same measurement protocol at the University Botanic Gardens in the autumn of 2024.  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 150\nColumns: 6\n$ sequence     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, …\n$ petal.width  <dbl> 9, 7, 11, 13, 11, 10, 12, 14, 9, 9, 9, 9, 11, 10, 15, 14, 11, 11, 9…\n$ petal.length <dbl> 16, 13, 23, 19, 16, 18, 20, 20, 15, 25, 17, 19, 21, 23, 20, 23, 19,…\n$ aperture     <dbl> 5, 4, 6, 6, 7, 6, 7, 8, 7, 6, 6, 6, 7, 8, 9, 7, 9, 8, 6, 7, 6, 7, 7…\n$ colour       <fct> white, pink, pink, white, pink, white, pink, white, white, pink, wh…\n$ group        <fct> epsilon, epsilon, epsilon, epsilon, epsilon, epsilon, epsilon, epsi…\n```\n\n\n:::\n:::\n\n:::\n\nA useful first step is to compute basic summaries and check that the categorical variables have the expected levels.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sequence     petal.width     petal.length     aperture        colour       group   \n Min.   : 1.0   Min.   : 4.00   Min.   : 9.0   Min.   : 4.000   pink :83   alpha  :30  \n 1st Qu.: 8.0   1st Qu.: 9.00   1st Qu.:18.0   1st Qu.: 6.000   white:67   beta   :30  \n Median :15.5   Median :10.00   Median :21.0   Median : 7.000              delta  :30  \n Mean   :15.5   Mean   :10.29   Mean   :20.5   Mean   : 7.173              epsilon:30  \n 3rd Qu.:23.0   3rd Qu.:12.00   3rd Qu.:23.0   3rd Qu.: 8.000              gamma  :30  \n Max.   :30.0   Max.   :19.00   Max.   :31.0   Max.   :11.000                          \n```\n\n\n:::\n:::\n\n\nThe summary above includes the sample mean of the continuous variables (e.g., `petal.width`) and the counts in each category for factors (e.g., `group`). \n\n:::{.callout-warning}\n## Missingness\n\nIn R, most functions will silently return `NA` if you have missing values. When computing summaries, decide in advance how you want to handle missingness (for example, removing incomplete rows for a particular calculation, or imputing missing values).\n:::\n\nA simple missingness check is:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |> summarise(across(everything(), ~ sum(is.na(.))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  sequence petal.width petal.length aperture colour group\n     <int>       <int>        <int>    <int>  <int> <int>\n1        0           0            0        0      0     0\n```\n\n\n:::\n:::\n\n\nIn EDA we typically combine numerical summaries with visual summaries. The next few sections outline basic visualisations. \n\n## Histograms and boxplots\n\nBelow are some standard plots for petal measurements. Histograms help you see shape (symmetry, skewness, multimodality), and boxplots highlight spread and potential outliers.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = petal.length)) +\n    geom_histogram(bins = 15)\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-hist-l-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = petal.width)) +\n    geom_histogram(bins = 15)\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-hist-w-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = aperture)) +\n    geom_histogram(bins = 8)\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-hist-a-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    pivot_longer(cols = c(petal.length, petal.width, aperture),\n        names_to = \"variable\",\n        values_to = \"value\") |>\n            ggplot(aes(x = variable, y = value)) +\n            geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-boxplot-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n:::{.callout-note}\n## Outliers are not necessarily errors\n\nA point that looks like an outlier is not automatically a data *error*. It may be a legitimate observation (for example, an unusually large flower), but it is always worth checking whether the measurement could have been recorded incorrectly (for example, were the correct units used).\n:::\n\n## Comparing groups\n\nA common EDA question is whether distributions differ across a group variable. Here, color is a natural grouping to start with.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = colour, y = petal.length)) +\n    geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cylcamen-boxplot-colour-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n## Relationships between variables\n\nFor two numerical variables, a scatter plot is usually the first plot to make.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = petal.length, y = petal.width)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-scatter-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\nSometimes it is helpful to add a grouping variable (here: `colour`) to see whether patterns differ between groups.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen |>\n    ggplot(aes(x = petal.length, y = petal.width, shape = colour)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/cyclamen-scatter-colour-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\n## Correlation as a summary of association\n\nCorrelation coefficients give a one-number summary of association between two numerical variables. Correlation does not imply causation!\n\nIn this module, we will use three common correlation coefficients:\n\n- **Pearson** correlation measures linear association (it is the default and is most directly connected to linear regression).\n- **Spearman** correlation measures monotone association by applying Pearson correlation to the ranks of the data.\n- **Kendall** correlation (Kendall's $\\tau$) measures association using concordant and discordant pairs, and also measures monotone association.\n\nIn EDA, it is common to compute Pearson, Spearman, and Kendall correlations together. If Pearson is small but Spearman/Kendall are large (in magnitude), that often suggests a relationship that is monotone but not well-approximated by a straight line.\n\n:::{.callout-tip}\n## A good EDA habit\n\n1. Make a scatter plot first.\n2. Compute Pearson correlation.\n3. If the relationship looks monotone but not linear, or if outliers look influential, also compute Spearman and Kendall as a sensitivity check.\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Pairwise scatterplot matrix for cyclamen petal width, petal length, and aperture diameter (using `GGally:ggpairs`). Points are shaped by flower colour. The diagonal panels show each variable's distribution (one density per colour); the upper panels summarise pairwise association using the *Pearson* correlation.](01-eda_files/figure-html/fig-cyclamen-pairwise-scatter-1.svg){#fig-cyclamen-pairwise-scatter fig-align='center' width=672}\n:::\n:::\n\n\nThe built-in function `cor` can be used to compute different correlation coefficients by specifying the method. For the cyclamen data, we will compute correlations between the three numerical flower measurements (here we exclude `sequence`, which is an index rather than a flower measurement).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen_num <- cyclamen |>\n    select(petal.width, petal.length, aperture)\n```\n:::\n\n\n### Pearson correlation matrix\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(cyclamen_num, use = \"complete.obs\", method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             petal.width petal.length  aperture\npetal.width    1.0000000    0.4474288 0.4277849\npetal.length   0.4474288    1.0000000 0.4238784\naperture       0.4277849    0.4238784 1.0000000\n```\n\n\n:::\n:::\n\n\n### Spearman correlation matrix\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(cyclamen_num, use = \"complete.obs\", method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             petal.width petal.length  aperture\npetal.width    1.0000000    0.4852075 0.4734670\npetal.length   0.4852075    1.0000000 0.4154867\naperture       0.4734670    0.4154867 1.0000000\n```\n\n\n:::\n:::\n\n\n### Kendall correlation matrix\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(cyclamen_num, use = \"complete.obs\", method = \"kendall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             petal.width petal.length  aperture\npetal.width    1.0000000    0.3689397 0.3751712\npetal.length   0.3689397    1.0000000 0.3353495\naperture       0.3751712    0.3353495 1.0000000\n```\n\n\n:::\n:::\n\n\nIf Pearson is close to $0$ but Spearman/Kendall are not, that often suggests a relationship that is monotone but not well-approximated by a straight line. If Pearson differs substantially from Spearman/Kendall, it is also worth checking for outliers.\n\n## Principal Component Analysis\n\nPrincipal Component Analysis (PCA) is an exploratory technique for understanding variation in multivariate numerical data. It constructs new variables (principal components) which are linear combinations of the original variables and which capture decreasing amounts of variation.\n\nFor cyclamen, we will apply PCA to the three numerical flower measurements: petal width, petal length, and aperture diameter.\n\n:::{.callout-warning}\n## Rescaling \n\nPCA is sensitive to the scale of the variables. When variables are measured on different scales (or have very different spreads), it is standard practice to *standardise* them before doing PCA. In `prcomp`, this is done with `scale. = TRUE`.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncyclamen_pca <- cyclamen |>\n    select(petal.width, petal.length, aperture, colour)\n\npca_fit <- cyclamen_pca |> \n    select(!colour) |>\n    prcomp(scale. = TRUE)\n\nsummary(pca_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                         PC1    PC2    PC3\nStandard deviation     1.366 0.7625 0.7432\nProportion of Variance 0.622 0.1938 0.1841\nCumulative Proportion  0.622 0.8159 1.0000\n```\n\n\n:::\n:::\n\n\n### Understanding the PCA summary \n\nFor three variables, PCA produces three principal components (PC1, PC2, PC3). The `summary()` output reports:\n\n- **Standard deviation** of each principal component: this is the spread of the data along that component.\n- **Proportion of Variance** explained by each component: the fraction of the total variability captured by that component.\n- **Cumulative Proportion** or the fraction captured by the first $k$ (reading left to right across the table).\n\nIn particular, the variance explained by PC$k$ is `pca_fit$sdev[k]^2`, and the proportion of variance explained is obtained by dividing by the total:\n$$\\mathrm{PVE}_k = \\frac{\\mathrm{sdev}_k^2}{\\sum_{j=1}^3 \\mathrm{sdev}_j^2} \\,.$$\nBecause we used `scale. = TRUE`, each original variable is standardised to have variance $1$, so the total variance is approximately $3$ (up to rounding). This is why $\\sum_{k=1}^3 \\mathrm{sdev}_k^2 \\approx 3$. \n\nFor the cylcamen data, the summary output shows:\n\n- PC1 explains about $62.2\\%$ of the variation in the three measurements.\n- PC2 explains about $19.4\\%$, and PC3 about $18.4\\%$.\n- The first two components together explain about $81.6\\%$ of the variation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npca_var <- pca_fit$sdev^2\npca_pve <- pca_var / sum(pca_var)\n\npve_tbl <-\n    tibble(\n        PC = factor(paste0(\"PC\", seq_along(pca_pve)),\n        levels = paste0(\"PC\", seq_along(pca_pve))),\n        proportion = pca_pve,\n        cumulative = cumsum(pca_pve)\n        )\n\npve_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  PC    proportion cumulative\n  <fct>      <dbl>      <dbl>\n1 PC1        0.622      0.622\n2 PC2        0.194      0.816\n3 PC3        0.184      1    \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![**Scree plot**: proportion of variance explained by each principal component in the cyclamen PCA.](01-eda_files/figure-html/fig-cyclamen-scree-1.svg){#fig-cyclamen-scree fig-align='center' width=672}\n:::\n:::\n\n\n## PCA scores plot\n\nA useful EDA plot is the projection of the observations onto the first two principal components. Here we colour by `colour` to check whether colour is associated with the main modes of variation in the measurements.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nscores <-\n    as_tibble(pca_fit$x) |>\n    bind_cols(cyclamen_pca |> select(colour))\n\nscores |>\n    ggplot(aes(x = PC1, y = PC2, shape = colour)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01-eda_files/figure-html/pca-scores-1.svg){fig-align='center' width=672}\n:::\n:::\n\n\nThe scatter plot above displays cyclamen PCA scores (PC1 vs PC2). Each point is a flower; points are shaped by flower colour.\n\n### Interpreting the principal components\n\nTo interpret the components, we examine the **loadings** (the coefficients defining each principal component as a linear combination of the original variables). In `prcomp`, these are stored in `pca_fit$rotation`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas_tibble(pca_fit$rotation, rownames = \"variable\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  variable       PC1    PC2     PC3\n  <chr>        <dbl>  <dbl>   <dbl>\n1 petal.width  0.581 -0.347 -0.736 \n2 petal.length 0.580 -0.458  0.674 \n3 aperture     0.571  0.818  0.0649\n```\n\n\n:::\n:::\n\n\nA loading with larger magnitude means that the corresponding variable contributes more strongly to that principal component.\n\n\n:::{.callout-warning}\n## PCA is not a hypothesis test\n\nPCA is an exploratory tool to help you describe patterns and identify dominant directions of variation. A common outcome is dimension reduction: here, PC1 and PC2 capture about $81.6\\%$ of the variation, so a two-dimensional view retains most of the information in the three measurements.\n:::",
    "supporting": [
      "01-eda_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}